USE [master]
GO

/****** Object:  Database [hrms]    Script Date: 11.05.2021 20:45:02 ******/
CREATE DATABASE [hrms]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'hrms', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\hrms.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'hrms_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\hrms_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [hrms].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [hrms] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [hrms] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [hrms] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [hrms] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [hrms] SET ARITHABORT OFF 
GO

ALTER DATABASE [hrms] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [hrms] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [hrms] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [hrms] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [hrms] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [hrms] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [hrms] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [hrms] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [hrms] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [hrms] SET  DISABLE_BROKER 
GO

ALTER DATABASE [hrms] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [hrms] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [hrms] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [hrms] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [hrms] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [hrms] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [hrms] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [hrms] SET RECOVERY FULL 
GO

ALTER DATABASE [hrms] SET  MULTI_USER 
GO

ALTER DATABASE [hrms] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [hrms] SET DB_CHAINING OFF 
GO

ALTER DATABASE [hrms] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [hrms] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [hrms] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [hrms] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [hrms] SET QUERY_STORE = OFF
GO

ALTER DATABASE [hrms] SET  READ_WRITE 
GO

